# Generated by Django 4.2.4 on 2023-08-29 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50, verbose_name='Название')),
                ('wrapper', models.CharField(max_length=50, verbose_name='Класс оболочка')),
                ('title', models.CharField(max_length=50, verbose_name='Класс загаловка')),
                ('price', models.CharField(max_length=50, verbose_name='Класс цены')),
                ('country_date', models.CharField(max_length=50, verbose_name='Класс города и времени')),
                ('url', models.CharField(max_length=200, verbose_name='Ксылка на категорию')),
                ('accept_button', models.CharField(max_length=200, verbose_name="Класс кнопки 'Принять куки'")),
            ],
        ),
        migrations.CreateModel(
            name='KufarItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_item', models.CharField(max_length=100, unique=True)),
                ('price', models.CharField(max_length=20, verbose_name='Цена')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('country', models.CharField(max_length=20, verbose_name='Город')),
                ('date', models.CharField(max_length=20, verbose_name='Дата создания, обновления')),
                ('url', models.CharField(max_length=200, verbose_name='Ссылка')),
                ('deleted', models.BooleanField()),
                ('category', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='parser.category', verbose_name='Категория')),
            ],
        ),
    ]
