# Generated by Django 4.2.4 on 2023-08-29 17:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категорию', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='kufaritems',
            options={'verbose_name': 'Товар куфара', 'verbose_name_plural': 'Товары куфара'},
        ),
        migrations.RenameField(
            model_name='kufaritems',
            old_name='category',
            new_name='cat',
        ),
        migrations.AddField(
            model_name='kufaritems',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Время создания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kufaritems',
            name='time_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Время изменения'),
        ),
        migrations.AlterField(
            model_name='category',
            name='url',
            field=models.CharField(max_length=200, verbose_name='Ссылка на категорию'),
        ),
        migrations.AlterField(
            model_name='kufaritems',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='kufaritems',
            name='id_item',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='kufaritems',
            name='price',
            field=models.IntegerField(verbose_name='Цена'),
        ),
    ]
