# Generated by Django 4.2.4 on 2023-10-18 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_remove_items_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botuser',
            name='telegram_id',
            field=models.IntegerField(unique=True),
        ),
    ]
