# Generated by Django 4.2.4 on 2023-10-18 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_alter_botuser_telegram_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='id_item',
            field=models.IntegerField(unique=True),
        ),
    ]
