# Generated by Django 4.2.4 on 2023-10-18 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_alter_items_id_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='items',
            old_name='id_item',
            new_name='pk_item',
        ),
    ]
